# Generated by Django 3.2.12 on 2022-05-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('poster_path', models.TextField(null=True)),
                ('release_date', models.TextField(default='', null=True)),
                ('title', models.CharField(max_length=50)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('genre', models.TextField(null=True)),
                ('tagline', models.TextField(null=True)),
                ('runtime', models.IntegerField(null=True)),
                ('trailer_key', models.TextField(null=True)),
            ],
        ),
    ]
