# Generated by Django 3.2.12 on 2022-05-26 07:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.TextField(null=True)),
                ('deathday', models.TextField(null=True)),
                ('actor_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('place_of_birth', models.TextField(null=True)),
                ('profile_path', models.TextField(null=True)),
                ('overview', models.TextField(null=True)),
                ('score', models.FloatField(blank=True, default=0)),
                ('like_users', models.ManyToManyField(related_name='actors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charactername', models.CharField(max_length=100, null=True)),
                ('score', models.FloatField(blank=True, default=0)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='actors.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='movie',
            field=models.ManyToManyField(through='actors.Character', to='movies.Movie'),
        ),
    ]
